services:
  - type: web
    name: iocl-backend
    env: python
    plan: free
    region: oregon
    rootDir: backend
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn train_model:app --host 0.0.0.0 --port 10000